### ISSUE TITLE
Makefile.am:78: error: CPPFLAGS_FOR_BUILD must be set with '=' before using '+='

### ISSUE THREAD

**Issue by buechling** [Gulden/gulden-official#18]
compilation will not work with actual version?

	~/guldencoin-official# ./autogen.sh
	libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, `build-aux'.
	libtoolize: copying file `build-aux/ltmain.sh'
	libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `build-aux/m4'.
	libtoolize: copying file `build-aux/m4/libtool.m4'
	libtoolize: copying file `build-aux/m4/ltoptions.m4'
	libtoolize: copying file `build-aux/m4/ltsugar.m4'
	libtoolize: copying file `build-aux/m4/ltversion.m4'
	libtoolize: copying file `build-aux/m4/lt~obsolete.m4'
	libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, `build-aux'.
	libtoolize: copying file `build-aux/ltmain.sh'
	libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `build-aux/m4'.
	libtoolize: copying file `build-aux/m4/libtool.m4'
	libtoolize: copying file `build-aux/m4/ltoptions.m4'
	libtoolize: copying file `build-aux/m4/ltsugar.m4'
	libtoolize: copying file `build-aux/m4/ltversion.m4'
	libtoolize: copying file `build-aux/m4/lt~obsolete.m4'
	Makefile.am:78: error: CPPFLAGS_FOR_BUILD must be set with '=' before using '+='
	Makefile.am:79: error: CFLAGS_FOR_BUILD must be set with '=' before using '+='
	autoreconf: automake failed with exit status: 1
	~/guldencoin-official# ./configure
	bash: ./configure: No such file or directory

**Comment by mjmacleod** [comment]
The problem is that your distro has old autotools on it.

See the README.md (https://github.com/Gulden/gulden-official/README.md) troubleshooting section - which in turn will point you to the old_autotools branch - using this branch (which is identical codewise but makes allowances for old autotools) should resolve the issue..

Note you will also need the correct boost and berkley DB - also discussed in the README.md

**Comment by buechling** [comment]
thank you! i can compile many altcoin without problems, libdb4.8 is a common problem. but indeed this solves the problem:

    git checkout old_autotools

**Comment by mjmacleod** [comment]
" i can compile many altcoins without problems"
Right, this is because most of them are using code that is multiple years out of date. (Old versions of bitcoin)

Gulden is based on the latest Bitcoin (0.13) and also contains a large amount of our own code and therefore has more modern requirements.

Anyway glad you have come right.

**Comment by pixelou** [comment]
The issue remains on archlinux which has the latest release of autotools (1.15 as of today). Could you clarify which version is expected for master branch?

**Comment by mjmacleod** [comment]
I believe it is autoconf that makes the difference and not automake, what version of autoconf do you have?
It works for me here on a system with automake 1.15, autoconf  2.69

I can't give you an exact 'expected' version as I have not had time to track this down to specific versions, I only know that it works on some distros and not on others.
I'm not an autotools expert and don't have enough time to look into it (yet) so I'm not entirely sure where the difference lies, whether it is the autoconf version or some global system setting that affects autoconf perhaps.

For those where it doesn't work the 'old_autotools' branch works fine - The two branches are identical except that 'old_autotools'  has a pre-generated 'build-aux' folder which helps sidestep this issue...

I'm hoping to fix this for the upcoming version 2 release but until then I don't have time to look into it, if you happen to have time to look into the issue more exact information and/or a proper fix would be appreciated, otherwise simply use the 'old_autotools' branch.

**Comment by verysexual** [comment]
Try compiling src/secp256k1

**Comment by mjmacleod** [comment]
Fixed in 2.0 release, until then use 'old_autotools' branch.
